use anchor_lang::prelude::*;
use anchor_spl::token::{self, Mint, Token, TokenAccount, Transfer};

declare_id!("DeAgEnt111111111111111111111111111111111111");

#[program]
pub mod deagent_protocol {
    use super::*;
    pub fn initialize_protocol(ctx: Context<InitializeProtocol>) -> Result<()> {
        let cfg = &mut ctx.accounts.protocol_config;
        cfg.authority = ctx.accounts.authority.key(); cfg.protocol_version = 1; cfg.paused = false; cfg.job_counter = 0; cfg.created_at = Clock::get()?.unix_timestamp;
        emit!(ProtocolInitialized { authority: cfg.authority, version: cfg.protocol_version }); Ok(())
    }
    pub fn register_agent(ctx: Context<RegisterAgent>, agent_id: String, agent_card_hash: [u8;32], metadata_uri: String, capabilities_hash: [u8;32]) -> Result<()> {
        require!(!ctx.accounts.protocol_config.paused, DeAgentError::ProtocolPaused); require!(agent_id.len() <= 64, DeAgentError::StringTooLong); require!(metadata_uri.len() <= 200, DeAgentError::StringTooLong);
        let a=&mut ctx.accounts.agent; a.owner=ctx.accounts.owner.key(); a.operational_wallet=ctx.accounts.operational_wallet.key(); a.treasury_wallet=ctx.accounts.treasury_wallet.key(); a.agent_id=agent_id; a.agent_card_hash=agent_card_hash; a.metadata_uri=metadata_uri; a.capabilities_hash=capabilities_hash; a.status=AgentStatus::Active; a.created_at=Clock::get()?.unix_timestamp; a.updated_at=a.created_at; a.bump=ctx.bumps.agent;
        emit!(AgentRegistered{agent:a.key(), owner:a.owner}); Ok(())
    }
    pub fn update_agent_metadata(ctx: Context<UpdateAgentMetadata>, agent_card_hash:[u8;32], metadata_uri:String, capabilities_hash:[u8;32]) -> Result<()> { require!(metadata_uri.len() <= 200, DeAgentError::StringTooLong); let a=&mut ctx.accounts.agent; a.agent_card_hash=agent_card_hash; a.metadata_uri=metadata_uri; a.capabilities_hash=capabilities_hash; a.updated_at=Clock::get()?.unix_timestamp; emit!(AgentUpdated{agent:a.key()}); Ok(()) }
    pub fn create_job(ctx: Context<CreateJob>, job_id:String, specification_hash:[u8;32], evidence_policy_hash:[u8;32], metadata_uri:String, payment_amount:u64, deadline:i64) -> Result<()> {
        require!(job_id.len() <= 64 && metadata_uri.len() <= 200, DeAgentError::StringTooLong); require!(payment_amount>0, DeAgentError::InvalidAmount); require!(deadline>Clock::get()?.unix_timestamp, DeAgentError::DeadlinePassed); require_keys_neq!(ctx.accounts.worker_agent.key(), ctx.accounts.evaluator_agent.key(), DeAgentError::WorkerCannotEvaluate);
        let j=&mut ctx.accounts.job; j.client=ctx.accounts.client.key(); j.worker_agent=ctx.accounts.worker_agent.key(); j.evaluator_agent=ctx.accounts.evaluator_agent.key(); j.job_id=job_id; j.specification_hash=specification_hash; j.evidence_policy_hash=evidence_policy_hash; j.metadata_uri=metadata_uri; j.payment_mint=ctx.accounts.payment_mint.key(); j.payment_amount=payment_amount; j.deadline=deadline; j.status=JobStatus::Draft; j.created_at=Clock::get()?.unix_timestamp; j.bump=ctx.bumps.job; ctx.accounts.protocol_config.job_counter=ctx.accounts.protocol_config.job_counter.checked_add(1).ok_or(DeAgentError::MathOverflow)?; emit!(JobCreated{job:j.key(), client:j.client, amount:payment_amount}); Ok(())
    }
    pub fn fund_job(ctx: Context<FundJob>) -> Result<()> { let amount=ctx.accounts.job.payment_amount; let job_key=ctx.accounts.job.key(); require!(ctx.accounts.job.status==JobStatus::Draft, DeAgentError::InvalidState); require_keys_eq!(ctx.accounts.job.client, ctx.accounts.client.key(), DeAgentError::Unauthorized); require_keys_eq!(ctx.accounts.job.payment_mint, ctx.accounts.client_token_account.mint, DeAgentError::IncorrectMint); require_keys_eq!(ctx.accounts.job.payment_mint, ctx.accounts.escrow_token_account.mint, DeAgentError::IncorrectMint); token::transfer(ctx.accounts.transfer_to_escrow(), amount)?; ctx.accounts.job.status=JobStatus::Funded; emit!(JobFunded{job:job_key, amount}); Ok(()) }
    pub fn accept_job(ctx: Context<AgentJobAction>) -> Result<()> { let j=&mut ctx.accounts.job; require!(j.status==JobStatus::Funded, DeAgentError::InvalidState); require_keys_eq!(j.worker_agent, ctx.accounts.agent.key(), DeAgentError::WrongWorker); require_keys_eq!(ctx.accounts.agent.operational_wallet, ctx.accounts.operator.key(), DeAgentError::Unauthorized); j.status=JobStatus::Accepted; j.accepted_at=Clock::get()?.unix_timestamp; emit!(JobAccepted{job:j.key(), worker:j.worker_agent}); Ok(()) }
    pub fn start_job(ctx: Context<AgentJobAction>) -> Result<()> { let j=&mut ctx.accounts.job; require!(j.status==JobStatus::Accepted, DeAgentError::InvalidState); j.status=JobStatus::InProgress; emit!(JobStarted{job:j.key()}); Ok(()) }
    pub fn submit_result(ctx: Context<AgentJobAction>, result_hash:[u8;32], result_uri:String) -> Result<()> { require!(result_uri.len()<=200, DeAgentError::StringTooLong); let j=&mut ctx.accounts.job; require!(j.status==JobStatus::InProgress, DeAgentError::InvalidState); require!(Clock::get()?.unix_timestamp<=j.deadline, DeAgentError::DeadlinePassed); j.result_hash=result_hash; j.result_uri=result_uri; j.status=JobStatus::Submitted; j.submitted_at=Clock::get()?.unix_timestamp; emit!(ResultSubmitted{job:j.key(), result_hash}); Ok(()) }
    pub fn submit_evaluation(ctx: Context<SubmitEvaluation>, decision:EvaluationDecision, score:u8, evidence_root:[u8;32], report_hash:[u8;32], report_uri:String) -> Result<()> { require!(score<=100, DeAgentError::InvalidScore); require!(report_uri.len()<=200, DeAgentError::StringTooLong); let j=&mut ctx.accounts.job; require!(j.status==JobStatus::Submitted, DeAgentError::InvalidState); require_keys_eq!(j.evaluator_agent, ctx.accounts.evaluator_agent.key(), DeAgentError::WrongEvaluator); require_keys_eq!(ctx.accounts.evaluator_agent.operational_wallet, ctx.accounts.evaluator.key(), DeAgentError::Unauthorized); let e=&mut ctx.accounts.evaluation; e.job=j.key(); e.evaluator=ctx.accounts.evaluator_agent.key(); e.decision=decision; e.score=score; e.evidence_root=evidence_root; e.report_hash=report_hash; e.report_uri=report_uri; e.created_at=Clock::get()?.unix_timestamp; e.bump=ctx.bumps.evaluation; j.evaluation_hash=report_hash; j.evaluation_score=score; j.evaluated_at=e.created_at; j.status=if decision==EvaluationDecision::Approved{JobStatus::Approved}else{JobStatus::Rejected}; emit!(EvaluationSubmitted{job:j.key(), decision, score}); Ok(()) }
    pub fn settle_job(ctx: Context<SettleJob>) -> Result<()> { let amount=ctx.accounts.job.payment_amount; let job_key=ctx.accounts.job.key(); require!(ctx.accounts.job.status==JobStatus::Approved, DeAgentError::InvalidState); require_keys_eq!(ctx.accounts.worker_treasury.key(), ctx.accounts.worker_agent.treasury_wallet, DeAgentError::ArbitraryDestination); let bump=[ctx.bumps.escrow_authority]; let seeds:&[&[u8]]=&[b"escrow", job_key.as_ref(), &bump]; token::transfer(ctx.accounts.pay_worker().with_signer(&[seeds]), amount)?; ctx.accounts.job.status=JobStatus::Paid; ctx.accounts.job.settled_at=Clock::get()?.unix_timestamp; emit!(JobSettled{job:job_key, amount}); Ok(()) }
    pub fn cancel_job(ctx: Context<ClientJobAction>) -> Result<()> { let j=&mut ctx.accounts.job; require!(j.status==JobStatus::Draft || j.status==JobStatus::Funded, DeAgentError::InvalidState); require_keys_eq!(j.client, ctx.accounts.client.key(), DeAgentError::Unauthorized); j.status=JobStatus::Cancelled; emit!(JobCancelled{job:j.key()}); Ok(()) }
    pub fn refund_job(ctx: Context<RefundJob>) -> Result<()> { let amount=ctx.accounts.job.payment_amount; let job_key=ctx.accounts.job.key(); let client=ctx.accounts.job.client; require!(ctx.accounts.job.status==JobStatus::Cancelled || ctx.accounts.job.status==JobStatus::Rejected, DeAgentError::InvalidState); require_keys_eq!(client, ctx.accounts.client.key(), DeAgentError::Unauthorized); require_keys_eq!(ctx.accounts.client_token_account.owner, client, DeAgentError::ArbitraryDestination); let bump=[ctx.bumps.escrow_authority]; let seeds:&[&[u8]]=&[b"escrow", job_key.as_ref(), &bump]; token::transfer(ctx.accounts.refund_client().with_signer(&[seeds]), amount)?; ctx.accounts.job.status=JobStatus::Refunded; emit!(JobRefunded{job:job_key, amount}); Ok(()) }
}
#[derive(Accounts)] pub struct InitializeProtocol<'info>{#[account(init,payer=authority,seeds=[b"protocol"],bump,space=8+ProtocolConfig::INIT_SPACE)] pub protocol_config:Account<'info,ProtocolConfig>,#[account(mut)] pub authority:Signer<'info>,pub system_program:Program<'info,System>}
#[derive(Accounts)] #[instruction(agent_id:String)] pub struct RegisterAgent<'info>{#[account(seeds=[b"protocol"],bump)] pub protocol_config:Account<'info,ProtocolConfig>,#[account(init,payer=owner,seeds=[b"agent",owner.key().as_ref(),agent_id.as_bytes()],bump,space=8+AgentAccount::INIT_SPACE)] pub agent:Account<'info,AgentAccount>,#[account(mut)] pub owner:Signer<'info>,/* CHECK: public wallet only */ pub operational_wallet:UncheckedAccount<'info>,/* CHECK: public wallet only */ pub treasury_wallet:UncheckedAccount<'info>,pub system_program:Program<'info,System>}
#[derive(Accounts)] pub struct UpdateAgentMetadata<'info>{#[account(mut,has_one=owner)] pub agent:Account<'info,AgentAccount>, pub owner:Signer<'info>}
#[derive(Accounts)] #[instruction(job_id:String)] pub struct CreateJob<'info>{#[account(mut,seeds=[b"protocol"],bump)] pub protocol_config:Account<'info,ProtocolConfig>,#[account(init,payer=client,seeds=[b"job",client.key().as_ref(),job_id.as_bytes()],bump,space=8+JobAccount::INIT_SPACE)] pub job:Account<'info,JobAccount>,#[account(mut)] pub client:Signer<'info>,pub worker_agent:Account<'info,AgentAccount>,pub evaluator_agent:Account<'info,AgentAccount>,pub payment_mint:Account<'info,Mint>,pub system_program:Program<'info,System>}
#[derive(Accounts)] pub struct FundJob<'info>{#[account(mut)] pub job:Account<'info,JobAccount>,#[account(mut)] pub client:Signer<'info>,#[account(mut,token::authority=client)] pub client_token_account:Account<'info,TokenAccount>,#[account(mut,token::mint=payment_mint,token::authority=escrow_authority)] pub escrow_token_account:Account<'info,TokenAccount>,pub payment_mint:Account<'info,Mint>,/* CHECK: PDA authority */ #[account(seeds=[b"escrow",job.key().as_ref()],bump)] pub escrow_authority:UncheckedAccount<'info>,pub token_program:Program<'info,Token>} impl<'info> FundJob<'info>{fn transfer_to_escrow(&self)->CpiContext<'_, '_, '_, 'info, Transfer<'info>>{CpiContext::new(self.token_program.to_account_info(),Transfer{from:self.client_token_account.to_account_info(),to:self.escrow_token_account.to_account_info(),authority:self.client.to_account_info()})}}
#[derive(Accounts)] pub struct AgentJobAction<'info>{#[account(mut)] pub job:Account<'info,JobAccount>,pub agent:Account<'info,AgentAccount>,pub operator:Signer<'info>}
#[derive(Accounts)] pub struct SubmitEvaluation<'info>{#[account(mut)] pub job:Account<'info,JobAccount>,#[account(init,payer=evaluator,seeds=[b"evaluation",job.key().as_ref(),evaluator_agent.key().as_ref()],bump,space=8+EvaluationAccount::INIT_SPACE)] pub evaluation:Account<'info,EvaluationAccount>,pub evaluator_agent:Account<'info,AgentAccount>,#[account(mut)] pub evaluator:Signer<'info>,pub system_program:Program<'info,System>}
#[derive(Accounts)] pub struct SettleJob<'info>{#[account(mut,has_one=worker_agent)] pub job:Account<'info,JobAccount>,pub worker_agent:Account<'info,AgentAccount>,#[account(mut)] pub escrow_token_account:Account<'info,TokenAccount>,#[account(mut)] pub worker_treasury:Account<'info,TokenAccount>,/* CHECK: PDA */ #[account(seeds=[b"escrow",job.key().as_ref()],bump)] pub escrow_authority:UncheckedAccount<'info>,pub token_program:Program<'info,Token>} impl<'info> SettleJob<'info>{fn pay_worker(&self)->CpiContext<'_, '_, '_, 'info, Transfer<'info>>{CpiContext::new(self.token_program.to_account_info(),Transfer{from:self.escrow_token_account.to_account_info(),to:self.worker_treasury.to_account_info(),authority:self.escrow_authority.to_account_info()})}}
#[derive(Accounts)] pub struct ClientJobAction<'info>{#[account(mut)] pub job:Account<'info,JobAccount>,pub client:Signer<'info>}
#[derive(Accounts)] pub struct RefundJob<'info>{#[account(mut)] pub job:Account<'info,JobAccount>,pub client:Signer<'info>,#[account(mut)] pub escrow_token_account:Account<'info,TokenAccount>,#[account(mut)] pub client_token_account:Account<'info,TokenAccount>,/* CHECK: PDA */ #[account(seeds=[b"escrow",job.key().as_ref()],bump)] pub escrow_authority:UncheckedAccount<'info>,pub token_program:Program<'info,Token>} impl<'info> RefundJob<'info>{fn refund_client(&self)->CpiContext<'_, '_, '_, 'info, Transfer<'info>>{CpiContext::new(self.token_program.to_account_info(),Transfer{from:self.escrow_token_account.to_account_info(),to:self.client_token_account.to_account_info(),authority:self.escrow_authority.to_account_info()})}}
#[account] #[derive(InitSpace)] pub struct ProtocolConfig{pub authority:Pubkey,pub protocol_version:u16,pub paused:bool,pub job_counter:u64,pub created_at:i64}
#[account] #[derive(InitSpace)] pub struct AgentAccount{pub owner:Pubkey,pub operational_wallet:Pubkey,pub treasury_wallet:Pubkey,#[max_len(64)] pub agent_id:String,pub agent_card_hash:[u8;32],#[max_len(200)] pub metadata_uri:String,pub capabilities_hash:[u8;32],pub status:AgentStatus,pub jobs_completed:u64,pub jobs_approved:u64,pub jobs_rejected:u64,pub total_value_completed:u64,pub created_at:i64,pub updated_at:i64,pub bump:u8}
#[account] #[derive(InitSpace)] pub struct JobAccount{pub client:Pubkey,pub worker_agent:Pubkey,pub evaluator_agent:Pubkey,#[max_len(64)] pub job_id:String,pub specification_hash:[u8;32],pub evidence_policy_hash:[u8;32],#[max_len(200)] pub metadata_uri:String,pub payment_mint:Pubkey,pub payment_amount:u64,pub deadline:i64,pub status:JobStatus,pub result_hash:[u8;32],#[max_len(200)] pub result_uri:String,pub evaluation_hash:[u8;32],pub evaluation_score:u8,pub created_at:i64,pub accepted_at:i64,pub submitted_at:i64,pub evaluated_at:i64,pub settled_at:i64,pub bump:u8}
#[account] #[derive(InitSpace)] pub struct EvaluationAccount{pub job:Pubkey,pub evaluator:Pubkey,pub decision:EvaluationDecision,pub score:u8,pub evidence_root:[u8;32],pub report_hash:[u8;32],#[max_len(200)] pub report_uri:String,pub created_at:i64,pub bump:u8}
#[derive(AnchorSerialize,AnchorDeserialize,Clone,Copy,PartialEq,Eq,InitSpace)] pub enum AgentStatus{Active,Paused,Retired}
#[derive(AnchorSerialize,AnchorDeserialize,Clone,Copy,PartialEq,Eq,InitSpace)] pub enum JobStatus{Draft,Funded,Accepted,InProgress,Submitted,Approved,Rejected,Cancelled,Disputed,Paid,Refunded}
#[derive(AnchorSerialize,AnchorDeserialize,Clone,Copy,PartialEq,Eq,InitSpace)] pub enum EvaluationDecision{Approved,Rejected,RevisionRequested,Inconclusive}
#[event] pub struct ProtocolInitialized{pub authority:Pubkey,pub version:u16} #[event] pub struct AgentRegistered{pub agent:Pubkey,pub owner:Pubkey} #[event] pub struct AgentUpdated{pub agent:Pubkey} #[event] pub struct JobCreated{pub job:Pubkey,pub client:Pubkey,pub amount:u64} #[event] pub struct JobFunded{pub job:Pubkey,pub amount:u64} #[event] pub struct JobAccepted{pub job:Pubkey,pub worker:Pubkey} #[event] pub struct JobStarted{pub job:Pubkey} #[event] pub struct ResultSubmitted{pub job:Pubkey,pub result_hash:[u8;32]} #[event] pub struct EvaluationSubmitted{pub job:Pubkey,pub decision:EvaluationDecision,pub score:u8} #[event] pub struct JobSettled{pub job:Pubkey,pub amount:u64} #[event] pub struct JobCancelled{pub job:Pubkey} #[event] pub struct JobRefunded{pub job:Pubkey,pub amount:u64}
#[error_code] pub enum DeAgentError{#[msg("Protocol is paused")] ProtocolPaused,#[msg("String too long")] StringTooLong,#[msg("Invalid amount")] InvalidAmount,#[msg("Deadline has passed")] DeadlinePassed,#[msg("Worker cannot evaluate own job")] WorkerCannotEvaluate,#[msg("Math overflow")] MathOverflow,#[msg("Invalid job state transition")] InvalidState,#[msg("Unauthorized signer")] Unauthorized,#[msg("Incorrect mint")] IncorrectMint,#[msg("Wrong worker")] WrongWorker,#[msg("Wrong evaluator")] WrongEvaluator,#[msg("Invalid score")] InvalidScore,#[msg("Arbitrary token destination rejected")] ArbitraryDestination}
