[features]
seeds = false
skip-lint = false

[programs.localnet]
openclaw_invocation = "5SfS5maRBYUE3sEnfRX4xjNzRpPNhXPEsQjboCVKb41e"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "anchor test"
